#define BLOCK_SIZE 512
#define TOTAL_BLOCKS 1024
#define TOTAL_INODES 128
#define SUPERBLOCK_BLOCK 0
#define INODE_BITMAP_BLOCK 1
#define DATA_BITMAP_BLOCK 2
#define MAX_BLOCKS_PER_INODE 16
#define MAX_INODES 128
#define MAX_DIR_ENTRIES 64

